[project]
name = "ai-researcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "langgraph-store-mongodb>=0.4.0",
]
